name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install tox and any other packages
        working-directory: "/home/runner/work/budget_django"
        run: ls && pip install -r requirements.txt
      - name: Run tests

        run: python script.py
